# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - frontinter

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_15bcbf2213c64773bf787d9e65381806 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_71dc4764cbd14836bb6d092ebe5ce6ef }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_15bcbf2213c64773bf787d9e65381806 }}/intermitente-front:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frontinter'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_22b8f261668241c29e86087b985d6f72 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_15bcbf2213c64773bf787d9e65381806 }}/intermitente-front:${{ github.sha }}'